// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YandexContestClient.Client.V2.Jupyter.Files.Item.Cancel;
using YandexContestClient.Client.V2.Jupyter.Files.Item.Confirm;
using YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload;
namespace YandexContestClient.Client.V2.Jupyter.Files.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\jupyter\files\{fileId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFileItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cancel property</summary>
        public global::YandexContestClient.Client.V2.Jupyter.Files.Item.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::YandexContestClient.Client.V2.Jupyter.Files.Item.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The confirm property</summary>
        public global::YandexContestClient.Client.V2.Jupyter.Files.Item.Confirm.ConfirmRequestBuilder Confirm
        {
            get => new global::YandexContestClient.Client.V2.Jupyter.Files.Item.Confirm.ConfirmRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The presignDownload property</summary>
        public global::YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload.PresignDownloadRequestBuilder PresignDownload
        {
            get => new global::YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload.PresignDownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.Item.WithFileItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFileItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter/files/{fileId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.Item.WithFileItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFileItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter/files/{fileId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
