// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YandexContestClient.Client.V2.WebIde.Ping;
using YandexContestClient.Client.V2.WebIde.Session;
using YandexContestClient.Client.V2.WebIde.Token;
namespace YandexContestClient.Client.V2.WebIde
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\web-ide
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebIdeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ping property</summary>
        public global::YandexContestClient.Client.V2.WebIde.Ping.PingRequestBuilder Ping
        {
            get => new global::YandexContestClient.Client.V2.WebIde.Ping.PingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The session property</summary>
        public global::YandexContestClient.Client.V2.WebIde.Session.SessionRequestBuilder Session
        {
            get => new global::YandexContestClient.Client.V2.WebIde.Session.SessionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::YandexContestClient.Client.V2.WebIde.Token.TokenRequestBuilder Token
        {
            get => new global::YandexContestClient.Client.V2.WebIde.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.WebIde.WebIdeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebIdeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/web-ide", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.WebIde.WebIdeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebIdeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/web-ide", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
