// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using YandexContestClient.Client.Models;
namespace YandexContestClient.Client.V2.Jupyter.Files.PresignUpload
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\jupyter\files\presign-upload
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PresignUploadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.PresignUpload.PresignUploadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PresignUploadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter/files/presign-upload{?userId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.PresignUpload.PresignUploadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PresignUploadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter/files/presign-upload{?userId*}", rawUrl)
        {
        }
        /// <summary>
        /// Issue a presigned PUT URL; ledger choice depends on principal role
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.Models.PresignJupyterUploadCommandResult"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::YandexContestClient.Client.Models.PresignJupyterUploadCommandResult?> PostAsync(global::YandexContestClient.Client.Models.PresignUploadRequest body, Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.PresignUpload.PresignUploadRequestBuilder.PresignUploadRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::YandexContestClient.Client.Models.PresignJupyterUploadCommandResult> PostAsync(global::YandexContestClient.Client.Models.PresignUploadRequest body, Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.PresignUpload.PresignUploadRequestBuilder.PresignUploadRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::YandexContestClient.Client.Models.PresignJupyterUploadCommandResult>(requestInfo, global::YandexContestClient.Client.Models.PresignJupyterUploadCommandResult.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Issue a presigned PUT URL; ledger choice depends on principal role
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::YandexContestClient.Client.Models.PresignUploadRequest body, Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.PresignUpload.PresignUploadRequestBuilder.PresignUploadRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::YandexContestClient.Client.Models.PresignUploadRequest body, Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.PresignUpload.PresignUploadRequestBuilder.PresignUploadRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.PresignUpload.PresignUploadRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::YandexContestClient.Client.V2.Jupyter.Files.PresignUpload.PresignUploadRequestBuilder WithUrl(string rawUrl)
        {
            return new global::YandexContestClient.Client.V2.Jupyter.Files.PresignUpload.PresignUploadRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Issue a presigned PUT URL; ledger choice depends on principal role
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PresignUploadRequestBuilderPostQueryParameters 
        {
            #pragma warning disable CS1591
            [QueryParameter("userId")]
            public long? UserId { get; set; }
            #pragma warning restore CS1591
        }
    }
}
#pragma warning restore CS0618
