// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using YandexContestClient.Client.Models;
namespace YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\jupyter\files\presign-upload-complete
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PresignUploadCompleteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete.PresignUploadCompleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PresignUploadCompleteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter/files/presign-upload-complete{?userId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete.PresignUploadCompleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PresignUploadCompleteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter/files/presign-upload-complete{?userId*}", rawUrl)
        {
        }
        /// <summary>
        /// Complete a multipart upload, transition row to uploaded
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.Models.PresignJupyterUploadCompleteCommandResult"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::YandexContestClient.Client.Models.PresignJupyterUploadCompleteCommandResult?> PostAsync(global::YandexContestClient.Client.Models.PresignUploadCompleteRequest body, Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete.PresignUploadCompleteRequestBuilder.PresignUploadCompleteRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::YandexContestClient.Client.Models.PresignJupyterUploadCompleteCommandResult> PostAsync(global::YandexContestClient.Client.Models.PresignUploadCompleteRequest body, Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete.PresignUploadCompleteRequestBuilder.PresignUploadCompleteRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::YandexContestClient.Client.Models.PresignJupyterUploadCompleteCommandResult>(requestInfo, global::YandexContestClient.Client.Models.PresignJupyterUploadCompleteCommandResult.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Complete a multipart upload, transition row to uploaded
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::YandexContestClient.Client.Models.PresignUploadCompleteRequest body, Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete.PresignUploadCompleteRequestBuilder.PresignUploadCompleteRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::YandexContestClient.Client.Models.PresignUploadCompleteRequest body, Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete.PresignUploadCompleteRequestBuilder.PresignUploadCompleteRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete.PresignUploadCompleteRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete.PresignUploadCompleteRequestBuilder WithUrl(string rawUrl)
        {
            return new global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete.PresignUploadCompleteRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Complete a multipart upload, transition row to uploaded
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PresignUploadCompleteRequestBuilderPostQueryParameters 
        {
            #pragma warning disable CS1591
            [QueryParameter("userId")]
            public long? UserId { get; set; }
            #pragma warning restore CS1591
        }
    }
}
#pragma warning restore CS0618
