// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Checker_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "STANDARD_CHECKER")]
        #pragma warning disable CS1591
        STANDARD_CHECKER,
        #pragma warning restore CS1591
        [EnumMember(Value = "TESTLIB_CHECKER")]
        #pragma warning disable CS1591
        TESTLIB_CHECKER,
        #pragma warning restore CS1591
        [EnumMember(Value = "EJUDGE_EXITCODE_CHECKER")]
        #pragma warning disable CS1591
        EJUDGE_EXITCODE_CHECKER,
        #pragma warning restore CS1591
        [EnumMember(Value = "TESTLIB_EXITCODE_CHECKER")]
        #pragma warning disable CS1591
        TESTLIB_EXITCODE_CHECKER,
        #pragma warning restore CS1591
    }
}
