// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Checker : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The compilerId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompilerId { get; set; }
#nullable restore
#else
        public string CompilerId { get; set; }
#endif
        /// <summary>The env property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::YandexContestClient.Client.Models.Checker_env? Env { get; set; }
#nullable restore
#else
        public global::YandexContestClient.Client.Models.Checker_env Env { get; set; }
#endif
        /// <summary>The paths property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Paths { get; set; }
#nullable restore
#else
        public List<string> Paths { get; set; }
#endif
        /// <summary>The standardChecker property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::YandexContestClient.Client.Models.StandardCheckerFile? StandardChecker { get; set; }
#nullable restore
#else
        public global::YandexContestClient.Client.Models.StandardCheckerFile StandardChecker { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::YandexContestClient.Client.Models.Checker_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.Models.Checker"/> and sets the default values.
        /// </summary>
        public Checker()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.Models.Checker"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::YandexContestClient.Client.Models.Checker CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::YandexContestClient.Client.Models.Checker();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "compilerId", n => { CompilerId = n.GetStringValue(); } },
                { "env", n => { Env = n.GetObjectValue<global::YandexContestClient.Client.Models.Checker_env>(global::YandexContestClient.Client.Models.Checker_env.CreateFromDiscriminatorValue); } },
                { "paths", n => { Paths = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "standardChecker", n => { StandardChecker = n.GetObjectValue<global::YandexContestClient.Client.Models.StandardCheckerFile>(global::YandexContestClient.Client.Models.StandardCheckerFile.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::YandexContestClient.Client.Models.Checker_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("compilerId", CompilerId);
            writer.WriteObjectValue<global::YandexContestClient.Client.Models.Checker_env>("env", Env);
            writer.WriteCollectionOfPrimitiveValues<string>("paths", Paths);
            writer.WriteObjectValue<global::YandexContestClient.Client.Models.StandardCheckerFile>("standardChecker", StandardChecker);
            writer.WriteEnumValue<global::YandexContestClient.Client.Models.Checker_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
