// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ContestDescription_standingsPlugin
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "calculator")]
        #pragma warning disable CS1591
        Calculator,
        #pragma warning restore CS1591
        [EnumMember(Value = "cpr")]
        #pragma warning disable CS1591
        Cpr,
        #pragma warning restore CS1591
        [EnumMember(Value = "ioi")]
        #pragma warning disable CS1591
        Ioi,
        #pragma warning restore CS1591
        [EnumMember(Value = "tcm/time")]
        #pragma warning disable CS1591
        TcmTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "tcm")]
        #pragma warning disable CS1591
        Tcm,
        #pragma warning restore CS1591
        [EnumMember(Value = "multiple_results")]
        #pragma warning disable CS1591
        Multiple_results,
        #pragma warning restore CS1591
        [EnumMember(Value = "shad")]
        #pragma warning disable CS1591
        Shad,
        #pragma warning restore CS1591
        [EnumMember(Value = "searchcup")]
        #pragma warning disable CS1591
        Searchcup,
        #pragma warning restore CS1591
        [EnumMember(Value = "acm")]
        #pragma warning disable CS1591
        Acm,
        #pragma warning restore CS1591
        [EnumMember(Value = "scoring")]
        #pragma warning disable CS1591
        Scoring,
        #pragma warning restore CS1591
    }
}
