// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateGroupRequest_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "INTERNAL")]
        #pragma warning disable CS1591
        INTERNAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "PASSPORT")]
        #pragma warning disable CS1591
        PASSPORT,
        #pragma warning restore CS1591
    }
}
