// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FileSettings : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The inputFile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InputFile { get; set; }
#nullable restore
#else
        public string InputFile { get; set; }
#endif
        /// <summary>The outputFile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutputFile { get; set; }
#nullable restore
#else
        public string OutputFile { get; set; }
#endif
        /// <summary>The redirectStdin property</summary>
        public bool? RedirectStdin { get; set; }
        /// <summary>The redirectStdout property</summary>
        public bool? RedirectStdout { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.Models.FileSettings"/> and sets the default values.
        /// </summary>
        public FileSettings()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.Models.FileSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::YandexContestClient.Client.Models.FileSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::YandexContestClient.Client.Models.FileSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "inputFile", n => { InputFile = n.GetStringValue(); } },
                { "outputFile", n => { OutputFile = n.GetStringValue(); } },
                { "redirectStdin", n => { RedirectStdin = n.GetBoolValue(); } },
                { "redirectStdout", n => { RedirectStdout = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("inputFile", InputFile);
            writer.WriteStringValue("outputFile", OutputFile);
            writer.WriteBoolValue("redirectStdin", RedirectStdin);
            writer.WriteBoolValue("redirectStdout", RedirectStdout);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
