// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GitlabTestEntry : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The memoryUsed property</summary>
        public long? MemoryUsed { get; set; }
        /// <summary>The runningTime property</summary>
        public long? RunningTime { get; set; }
        /// <summary>The score property</summary>
        public double? Score { get; set; }
        /// <summary>The testName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TestName { get; set; }
#nullable restore
#else
        public string TestName { get; set; }
#endif
        /// <summary>The testsetName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TestsetName { get; set; }
#nullable restore
#else
        public string TestsetName { get; set; }
#endif
        /// <summary>The verdict property</summary>
        public global::YandexContestClient.Client.Models.GitlabTestEntry_verdict? Verdict { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.Models.GitlabTestEntry"/> and sets the default values.
        /// </summary>
        public GitlabTestEntry()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.Models.GitlabTestEntry"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::YandexContestClient.Client.Models.GitlabTestEntry CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::YandexContestClient.Client.Models.GitlabTestEntry();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "memoryUsed", n => { MemoryUsed = n.GetLongValue(); } },
                { "runningTime", n => { RunningTime = n.GetLongValue(); } },
                { "score", n => { Score = n.GetDoubleValue(); } },
                { "testName", n => { TestName = n.GetStringValue(); } },
                { "testsetName", n => { TestsetName = n.GetStringValue(); } },
                { "verdict", n => { Verdict = n.GetEnumValue<global::YandexContestClient.Client.Models.GitlabTestEntry_verdict>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("memoryUsed", MemoryUsed);
            writer.WriteLongValue("runningTime", RunningTime);
            writer.WriteDoubleValue("score", Score);
            writer.WriteStringValue("testName", TestName);
            writer.WriteStringValue("testsetName", TestsetName);
            writer.WriteEnumValue<global::YandexContestClient.Client.Models.GitlabTestEntry_verdict>("verdict", Verdict);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
