// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GitlabReport_verdict
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CompilationError")]
        #pragma warning disable CS1591
        CompilationError,
        #pragma warning restore CS1591
        [EnumMember(Value = "PrecompileCheckFailed")]
        #pragma warning disable CS1591
        PrecompileCheckFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "Crash")]
        #pragma warning disable CS1591
        Crash,
        #pragma warning restore CS1591
    }
}
