// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GitlabUploadArtifactRequest_testDataType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "INPUT")]
        #pragma warning disable CS1591
        INPUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "OUTPUT")]
        #pragma warning disable CS1591
        OUTPUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "ANSWER")]
        #pragma warning disable CS1591
        ANSWER,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHECKER_ERROR")]
        #pragma warning disable CS1591
        CHECKER_ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
    }
}
