// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GitlabTestEntry_verdict
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "OK")]
        #pragma warning disable CS1591
        OK,
        #pragma warning restore CS1591
        [EnumMember(Value = "WrongAnswer")]
        #pragma warning disable CS1591
        WrongAnswer,
        #pragma warning restore CS1591
        [EnumMember(Value = "PresentationError")]
        #pragma warning disable CS1591
        PresentationError,
        #pragma warning restore CS1591
        [EnumMember(Value = "TimeLimitExceeded")]
        #pragma warning disable CS1591
        TimeLimitExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "MemoryLimitExceeded")]
        #pragma warning disable CS1591
        MemoryLimitExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "IdlenessLimitExceeded")]
        #pragma warning disable CS1591
        IdlenessLimitExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "OutputLimitExceeded")]
        #pragma warning disable CS1591
        OutputLimitExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "RuntimeError")]
        #pragma warning disable CS1591
        RuntimeError,
        #pragma warning restore CS1591
        [EnumMember(Value = "Crash")]
        #pragma warning disable CS1591
        Crash,
        #pragma warning restore CS1591
    }
}
