// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PresignedProblemFile : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The children property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::YandexContestClient.Client.Models.PresignedProblemFile>? Children { get; set; }
#nullable restore
#else
        public List<global::YandexContestClient.Client.Models.PresignedProblemFile> Children { get; set; }
#endif
        /// <summary>The file property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::YandexContestClient.Client.Models.PresignedS3File? File { get; set; }
#nullable restore
#else
        public global::YandexContestClient.Client.Models.PresignedS3File File { get; set; }
#endif
        /// <summary>The isDirectory property</summary>
        public bool? IsDirectory { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.Models.PresignedProblemFile"/> and sets the default values.
        /// </summary>
        public PresignedProblemFile()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.Models.PresignedProblemFile"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::YandexContestClient.Client.Models.PresignedProblemFile CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::YandexContestClient.Client.Models.PresignedProblemFile();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "children", n => { Children = n.GetCollectionOfObjectValues<global::YandexContestClient.Client.Models.PresignedProblemFile>(global::YandexContestClient.Client.Models.PresignedProblemFile.CreateFromDiscriminatorValue)?.AsList(); } },
                { "file", n => { File = n.GetObjectValue<global::YandexContestClient.Client.Models.PresignedS3File>(global::YandexContestClient.Client.Models.PresignedS3File.CreateFromDiscriminatorValue); } },
                { "isDirectory", n => { IsDirectory = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::YandexContestClient.Client.Models.PresignedProblemFile>("children", Children);
            writer.WriteObjectValue<global::YandexContestClient.Client.Models.PresignedS3File>("file", File);
            writer.WriteBoolValue("isDirectory", IsDirectory);
            writer.WriteStringValue("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
