// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PresignJupyterUploadInitCommandResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The expiresAtEpochSecond property</summary>
        public long? ExpiresAtEpochSecond { get; set; }
        /// <summary>The fileId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileId { get; set; }
#nullable restore
#else
        public string FileId { get; set; }
#endif
        /// <summary>The kind property</summary>
        public global::YandexContestClient.Client.Models.PresignJupyterUploadInitCommandResult_kind? Kind { get; set; }
        /// <summary>The partCount property</summary>
        public int? PartCount { get; set; }
        /// <summary>The partSizeBytes property</summary>
        public long? PartSizeBytes { get; set; }
        /// <summary>The partUrls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PartUrls { get; set; }
#nullable restore
#else
        public List<string> PartUrls { get; set; }
#endif
        /// <summary>The uploadId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UploadId { get; set; }
#nullable restore
#else
        public string UploadId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.Models.PresignJupyterUploadInitCommandResult"/> and sets the default values.
        /// </summary>
        public PresignJupyterUploadInitCommandResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.Models.PresignJupyterUploadInitCommandResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::YandexContestClient.Client.Models.PresignJupyterUploadInitCommandResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::YandexContestClient.Client.Models.PresignJupyterUploadInitCommandResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "expiresAtEpochSecond", n => { ExpiresAtEpochSecond = n.GetLongValue(); } },
                { "fileId", n => { FileId = n.GetStringValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::YandexContestClient.Client.Models.PresignJupyterUploadInitCommandResult_kind>(); } },
                { "partCount", n => { PartCount = n.GetIntValue(); } },
                { "partSizeBytes", n => { PartSizeBytes = n.GetLongValue(); } },
                { "partUrls", n => { PartUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "uploadId", n => { UploadId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("expiresAtEpochSecond", ExpiresAtEpochSecond);
            writer.WriteStringValue("fileId", FileId);
            writer.WriteEnumValue<global::YandexContestClient.Client.Models.PresignJupyterUploadInitCommandResult_kind>("kind", Kind);
            writer.WriteIntValue("partCount", PartCount);
            writer.WriteLongValue("partSizeBytes", PartSizeBytes);
            writer.WriteCollectionOfPrimitiveValues<string>("partUrls", PartUrls);
            writer.WriteStringValue("uploadId", UploadId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
