// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PresignJupyterUploadInitCommandResult_kind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "USER")]
        #pragma warning disable CS1591
        USER,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEMPLATE")]
        #pragma warning disable CS1591
        TEMPLATE,
        #pragma warning restore CS1591
    }
}
