// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProblemSettings : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The checker property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::YandexContestClient.Client.Models.Checker? Checker { get; set; }
#nullable restore
#else
        public global::YandexContestClient.Client.Models.Checker Checker { get; set; }
#endif
        /// <summary>The compilationLimits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::YandexContestClient.Client.Models.ResourceLimits? CompilationLimits { get; set; }
#nullable restore
#else
        public global::YandexContestClient.Client.Models.ResourceLimits CompilationLimits { get; set; }
#endif
        /// <summary>The compileFiles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CompileFiles { get; set; }
#nullable restore
#else
        public List<string> CompileFiles { get; set; }
#endif
        /// <summary>The customCompilationLimits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::YandexContestClient.Client.Models.ProblemSettings_customCompilationLimits? CustomCompilationLimits { get; set; }
#nullable restore
#else
        public global::YandexContestClient.Client.Models.ProblemSettings_customCompilationLimits CustomCompilationLimits { get; set; }
#endif
        /// <summary>The customInvocationLimits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::YandexContestClient.Client.Models.ProblemSettings_customInvocationLimits? CustomInvocationLimits { get; set; }
#nullable restore
#else
        public global::YandexContestClient.Client.Models.ProblemSettings_customInvocationLimits CustomInvocationLimits { get; set; }
#endif
        /// <summary>The fileSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::YandexContestClient.Client.Models.FileSettings? FileSettings { get; set; }
#nullable restore
#else
        public global::YandexContestClient.Client.Models.FileSettings FileSettings { get; set; }
#endif
        /// <summary>The invocationLimits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::YandexContestClient.Client.Models.ResourceLimits? InvocationLimits { get; set; }
#nullable restore
#else
        public global::YandexContestClient.Client.Models.ResourceLimits InvocationLimits { get; set; }
#endif
        /// <summary>The problemType property</summary>
        public global::YandexContestClient.Client.Models.ProblemSettings_problemType? ProblemType { get; set; }
        /// <summary>The runtimeFiles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RuntimeFiles { get; set; }
#nullable restore
#else
        public List<string> RuntimeFiles { get; set; }
#endif
        /// <summary>The testsets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::YandexContestClient.Client.Models.TestsetPojo>? Testsets { get; set; }
#nullable restore
#else
        public List<global::YandexContestClient.Client.Models.TestsetPojo> Testsets { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.Models.ProblemSettings"/> and sets the default values.
        /// </summary>
        public ProblemSettings()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.Models.ProblemSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::YandexContestClient.Client.Models.ProblemSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::YandexContestClient.Client.Models.ProblemSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checker", n => { Checker = n.GetObjectValue<global::YandexContestClient.Client.Models.Checker>(global::YandexContestClient.Client.Models.Checker.CreateFromDiscriminatorValue); } },
                { "compilationLimits", n => { CompilationLimits = n.GetObjectValue<global::YandexContestClient.Client.Models.ResourceLimits>(global::YandexContestClient.Client.Models.ResourceLimits.CreateFromDiscriminatorValue); } },
                { "compileFiles", n => { CompileFiles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "customCompilationLimits", n => { CustomCompilationLimits = n.GetObjectValue<global::YandexContestClient.Client.Models.ProblemSettings_customCompilationLimits>(global::YandexContestClient.Client.Models.ProblemSettings_customCompilationLimits.CreateFromDiscriminatorValue); } },
                { "customInvocationLimits", n => { CustomInvocationLimits = n.GetObjectValue<global::YandexContestClient.Client.Models.ProblemSettings_customInvocationLimits>(global::YandexContestClient.Client.Models.ProblemSettings_customInvocationLimits.CreateFromDiscriminatorValue); } },
                { "fileSettings", n => { FileSettings = n.GetObjectValue<global::YandexContestClient.Client.Models.FileSettings>(global::YandexContestClient.Client.Models.FileSettings.CreateFromDiscriminatorValue); } },
                { "invocationLimits", n => { InvocationLimits = n.GetObjectValue<global::YandexContestClient.Client.Models.ResourceLimits>(global::YandexContestClient.Client.Models.ResourceLimits.CreateFromDiscriminatorValue); } },
                { "problemType", n => { ProblemType = n.GetEnumValue<global::YandexContestClient.Client.Models.ProblemSettings_problemType>(); } },
                { "runtimeFiles", n => { RuntimeFiles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "testsets", n => { Testsets = n.GetCollectionOfObjectValues<global::YandexContestClient.Client.Models.TestsetPojo>(global::YandexContestClient.Client.Models.TestsetPojo.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::YandexContestClient.Client.Models.Checker>("checker", Checker);
            writer.WriteObjectValue<global::YandexContestClient.Client.Models.ResourceLimits>("compilationLimits", CompilationLimits);
            writer.WriteCollectionOfPrimitiveValues<string>("compileFiles", CompileFiles);
            writer.WriteObjectValue<global::YandexContestClient.Client.Models.ProblemSettings_customCompilationLimits>("customCompilationLimits", CustomCompilationLimits);
            writer.WriteObjectValue<global::YandexContestClient.Client.Models.ProblemSettings_customInvocationLimits>("customInvocationLimits", CustomInvocationLimits);
            writer.WriteObjectValue<global::YandexContestClient.Client.Models.FileSettings>("fileSettings", FileSettings);
            writer.WriteObjectValue<global::YandexContestClient.Client.Models.ResourceLimits>("invocationLimits", InvocationLimits);
            writer.WriteEnumValue<global::YandexContestClient.Client.Models.ProblemSettings_problemType>("problemType", ProblemType);
            writer.WriteCollectionOfPrimitiveValues<string>("runtimeFiles", RuntimeFiles);
            writer.WriteCollectionOfObjectValues<global::YandexContestClient.Client.Models.TestsetPojo>("testsets", Testsets);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
