// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProblemSettings_problemType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PROBLEM_WITH_CHECKER")]
        #pragma warning disable CS1591
        PROBLEM_WITH_CHECKER,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTERACTIVE_PROBLEM")]
        #pragma warning disable CS1591
        INTERACTIVE_PROBLEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEXT_ANSWER_PROBLEM")]
        #pragma warning disable CS1591
        TEXT_ANSWER_PROBLEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEST_PROBLEM")]
        #pragma warning disable CS1591
        TEST_PROBLEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROBLEM_WITH_CUSTOM_CONFIG")]
        #pragma warning disable CS1591
        PROBLEM_WITH_CUSTOM_CONFIG,
        #pragma warning restore CS1591
        [EnumMember(Value = "RUN_TWICE_PROBLEM")]
        #pragma warning disable CS1591
        RUN_TWICE_PROBLEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "PICTURE_PROBLEM")]
        #pragma warning disable CS1591
        PICTURE_PROBLEM,
        #pragma warning restore CS1591
    }
}
