// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WebIdeSession_unavailableReason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "FEATURE_DISABLED")]
        #pragma warning disable CS1591
        FEATURE_DISABLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_A_GITLAB_PROBLEM")]
        #pragma warning disable CS1591
        NOT_A_GITLAB_PROBLEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROBLEM_NOT_IN_CONTEST")]
        #pragma warning disable CS1591
        PROBLEM_NOT_IN_CONTEST,
        #pragma warning restore CS1591
        [EnumMember(Value = "LANGUAGE_NOT_ALLOWED")]
        #pragma warning disable CS1591
        LANGUAGE_NOT_ALLOWED,
        #pragma warning restore CS1591
        [EnumMember(Value = "REPOSITORY_DISABLED")]
        #pragma warning disable CS1591
        REPOSITORY_DISABLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "REPOSITORY_INITIALIZING")]
        #pragma warning disable CS1591
        REPOSITORY_INITIALIZING,
        #pragma warning restore CS1591
        [EnumMember(Value = "REPOSITORY_FAILED")]
        #pragma warning disable CS1591
        REPOSITORY_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "GITLAB_ENVIRONMENT_OUTDATED")]
        #pragma warning disable CS1591
        GITLAB_ENVIRONMENT_OUTDATED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTICIPATION_NOT_STARTED")]
        #pragma warning disable CS1591
        PARTICIPATION_NOT_STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTICIPATION_CLOSED")]
        #pragma warning disable CS1591
        PARTICIPATION_CLOSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NETWORK_RESTRICTED")]
        #pragma warning disable CS1591
        NETWORK_RESTRICTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEFAULT_BRANCH_UNKNOWN")]
        #pragma warning disable CS1591
        DEFAULT_BRANCH_UNKNOWN,
        #pragma warning restore CS1591
    }
}
