// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace YandexContestClient.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebIdeSession : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The available property</summary>
        public bool? Available { get; set; }
        /// <summary>The embedderOriginUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmbedderOriginUrl { get; set; }
#nullable restore
#else
        public string EmbedderOriginUrl { get; set; }
#endif
        /// <summary>The extensionsHostBaseUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExtensionsHostBaseUrl { get; set; }
#nullable restore
#else
        public string ExtensionsHostBaseUrl { get; set; }
#endif
        /// <summary>The filePath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FilePath { get; set; }
#nullable restore
#else
        public string FilePath { get; set; }
#endif
        /// <summary>The gitlabUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GitlabUrl { get; set; }
#nullable restore
#else
        public string GitlabUrl { get; set; }
#endif
        /// <summary>The login property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Login { get; set; }
#nullable restore
#else
        public string Login { get; set; }
#endif
        /// <summary>The problemName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProblemName { get; set; }
#nullable restore
#else
        public string ProblemName { get; set; }
#endif
        /// <summary>The projectId property</summary>
        public long? ProjectId { get; set; }
        /// <summary>The projectPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectPath { get; set; }
#nullable restore
#else
        public string ProjectPath { get; set; }
#endif
        /// <summary>The retryAfterSeconds property</summary>
        public int? RetryAfterSeconds { get; set; }
        /// <summary>The unavailableReason property</summary>
        public global::YandexContestClient.Client.Models.WebIdeSession_unavailableReason? UnavailableReason { get; set; }
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>The workbenchBaseUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkbenchBaseUrl { get; set; }
#nullable restore
#else
        public string WorkbenchBaseUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.Models.WebIdeSession"/> and sets the default values.
        /// </summary>
        public WebIdeSession()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.Models.WebIdeSession"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::YandexContestClient.Client.Models.WebIdeSession CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::YandexContestClient.Client.Models.WebIdeSession();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "available", n => { Available = n.GetBoolValue(); } },
                { "embedderOriginUrl", n => { EmbedderOriginUrl = n.GetStringValue(); } },
                { "extensionsHostBaseUrl", n => { ExtensionsHostBaseUrl = n.GetStringValue(); } },
                { "filePath", n => { FilePath = n.GetStringValue(); } },
                { "gitlabUrl", n => { GitlabUrl = n.GetStringValue(); } },
                { "login", n => { Login = n.GetStringValue(); } },
                { "problemName", n => { ProblemName = n.GetStringValue(); } },
                { "projectId", n => { ProjectId = n.GetLongValue(); } },
                { "projectPath", n => { ProjectPath = n.GetStringValue(); } },
                { "retryAfterSeconds", n => { RetryAfterSeconds = n.GetIntValue(); } },
                { "unavailableReason", n => { UnavailableReason = n.GetEnumValue<global::YandexContestClient.Client.Models.WebIdeSession_unavailableReason>(); } },
                { "version", n => { Version = n.GetStringValue(); } },
                { "workbenchBaseUrl", n => { WorkbenchBaseUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("available", Available);
            writer.WriteStringValue("embedderOriginUrl", EmbedderOriginUrl);
            writer.WriteStringValue("extensionsHostBaseUrl", ExtensionsHostBaseUrl);
            writer.WriteStringValue("filePath", FilePath);
            writer.WriteStringValue("gitlabUrl", GitlabUrl);
            writer.WriteStringValue("login", Login);
            writer.WriteStringValue("problemName", ProblemName);
            writer.WriteLongValue("projectId", ProjectId);
            writer.WriteStringValue("projectPath", ProjectPath);
            writer.WriteIntValue("retryAfterSeconds", RetryAfterSeconds);
            writer.WriteEnumValue<global::YandexContestClient.Client.Models.WebIdeSession_unavailableReason>("unavailableReason", UnavailableReason);
            writer.WriteStringValue("version", Version);
            writer.WriteStringValue("workbenchBaseUrl", WorkbenchBaseUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
