// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YandexContestClient.Client.Gitlab.Report;
using YandexContestClient.Client.Gitlab.UploadArtifact;
namespace YandexContestClient.Client.Gitlab
{
    /// <summary>
    /// Builds and executes requests for operations under \gitlab
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GitlabRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The report property</summary>
        public global::YandexContestClient.Client.Gitlab.Report.ReportRequestBuilder Report
        {
            get => new global::YandexContestClient.Client.Gitlab.Report.ReportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The uploadArtifact property</summary>
        public global::YandexContestClient.Client.Gitlab.UploadArtifact.UploadArtifactRequestBuilder UploadArtifact
        {
            get => new global::YandexContestClient.Client.Gitlab.UploadArtifact.UploadArtifactRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.Gitlab.GitlabRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GitlabRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gitlab", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.Gitlab.GitlabRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GitlabRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gitlab", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
