// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YandexContestClient.Client.V2.Contests.Neurips.Item;
namespace YandexContestClient.Client.V2.Contests.Neurips
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\contests\neurips
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NeuripsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the YandexContestClient.Client.v2.contests.neurips.item collection</summary>
        /// <param name="position">contestId</param>
        /// <returns>A <see cref="global::YandexContestClient.Client.V2.Contests.Neurips.Item.WithContestItemRequestBuilder"/></returns>
        public global::YandexContestClient.Client.V2.Contests.Neurips.Item.WithContestItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("contestId", position);
                return new global::YandexContestClient.Client.V2.Contests.Neurips.Item.WithContestItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Contests.Neurips.NeuripsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NeuripsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/contests/neurips", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Contests.Neurips.NeuripsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NeuripsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/contests/neurips", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
