// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YandexContestClient.Client.Problems.Item.Item;
namespace YandexContestClient.Client.Problems.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \problems\{id1}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProblemsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the YandexContestClient.Client.problems.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::YandexContestClient.Client.Problems.Item.Item.Id1ItemRequestBuilder"/></returns>
        public global::YandexContestClient.Client.Problems.Item.Item.Id1ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id2", position);
                return new global::YandexContestClient.Client.Problems.Item.Item.Id1ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.Problems.Item.ProblemsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProblemsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/problems/{id1}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.Problems.Item.ProblemsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProblemsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/problems/{id1}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
