// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YandexContestClient.Client.V2.Jupyter.Files.Item;
using YandexContestClient.Client.V2.Jupyter.Files.PresignUpload;
using YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete;
using YandexContestClient.Client.V2.Jupyter.Files.PresignUploadInit;
using YandexContestClient.Client.V2.Jupyter.Files.ServerFiles;
namespace YandexContestClient.Client.V2.Jupyter.Files
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\jupyter\files
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The presignUpload property</summary>
        public global::YandexContestClient.Client.V2.Jupyter.Files.PresignUpload.PresignUploadRequestBuilder PresignUpload
        {
            get => new global::YandexContestClient.Client.V2.Jupyter.Files.PresignUpload.PresignUploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The presignUploadComplete property</summary>
        public global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete.PresignUploadCompleteRequestBuilder PresignUploadComplete
        {
            get => new global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadComplete.PresignUploadCompleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The presignUploadInit property</summary>
        public global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadInit.PresignUploadInitRequestBuilder PresignUploadInit
        {
            get => new global::YandexContestClient.Client.V2.Jupyter.Files.PresignUploadInit.PresignUploadInitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The serverFiles property</summary>
        public global::YandexContestClient.Client.V2.Jupyter.Files.ServerFiles.ServerFilesRequestBuilder ServerFiles
        {
            get => new global::YandexContestClient.Client.V2.Jupyter.Files.ServerFiles.ServerFilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the YandexContestClient.Client.v2.jupyter.files.item collection</summary>
        /// <param name="position">fileId</param>
        /// <returns>A <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.Item.WithFileItemRequestBuilder"/></returns>
        public global::YandexContestClient.Client.V2.Jupyter.Files.Item.WithFileItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("fileId", position);
                return new global::YandexContestClient.Client.V2.Jupyter.Files.Item.WithFileItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter/files", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter/files", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
