// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using YandexContestClient.Client.Models;
namespace YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\jupyter\files\{fileId}\presign-download
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PresignDownloadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload.PresignDownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PresignDownloadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter/files/{fileId}/presign-download{?userId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload.PresignDownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PresignDownloadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter/files/{fileId}/presign-download{?userId*}", rawUrl)
        {
        }
        /// <summary>
        /// Issue a short-lived presigned GET URL (searches both ledgers)
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.Models.GetJupyterPresignDownloadQueryResult"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::YandexContestClient.Client.Models.GetJupyterPresignDownloadQueryResult?> GetAsync(Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload.PresignDownloadRequestBuilder.PresignDownloadRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::YandexContestClient.Client.Models.GetJupyterPresignDownloadQueryResult> GetAsync(Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload.PresignDownloadRequestBuilder.PresignDownloadRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::YandexContestClient.Client.Models.GetJupyterPresignDownloadQueryResult>(requestInfo, global::YandexContestClient.Client.Models.GetJupyterPresignDownloadQueryResult.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Issue a short-lived presigned GET URL (searches both ledgers)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload.PresignDownloadRequestBuilder.PresignDownloadRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload.PresignDownloadRequestBuilder.PresignDownloadRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload.PresignDownloadRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload.PresignDownloadRequestBuilder WithUrl(string rawUrl)
        {
            return new global::YandexContestClient.Client.V2.Jupyter.Files.Item.PresignDownload.PresignDownloadRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Issue a short-lived presigned GET URL (searches both ledgers)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PresignDownloadRequestBuilderGetQueryParameters 
        {
            #pragma warning disable CS1591
            [QueryParameter("userId")]
            public long? UserId { get; set; }
            #pragma warning restore CS1591
        }
    }
}
#pragma warning restore CS0618
