// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YandexContestClient.Client.V2.Competitions;
using YandexContestClient.Client.V2.Compilers;
using YandexContestClient.Client.V2.Contests;
using YandexContestClient.Client.V2.Gitlab;
using YandexContestClient.Client.V2.Groups;
using YandexContestClient.Client.V2.Participants;
using YandexContestClient.Client.V2.Problems;
using YandexContestClient.Client.V2.Service;
using YandexContestClient.Client.V2.Submissions;
using YandexContestClient.Client.V2.Teams;
using YandexContestClient.Client.V2.User;
namespace YandexContestClient.Client.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The competitions property</summary>
        public global::YandexContestClient.Client.V2.Competitions.CompetitionsRequestBuilder Competitions
        {
            get => new global::YandexContestClient.Client.V2.Competitions.CompetitionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The compilers property</summary>
        public global::YandexContestClient.Client.V2.Compilers.CompilersRequestBuilder Compilers
        {
            get => new global::YandexContestClient.Client.V2.Compilers.CompilersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contests property</summary>
        public global::YandexContestClient.Client.V2.Contests.ContestsRequestBuilder Contests
        {
            get => new global::YandexContestClient.Client.V2.Contests.ContestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gitlab property</summary>
        public global::YandexContestClient.Client.V2.Gitlab.GitlabRequestBuilder Gitlab
        {
            get => new global::YandexContestClient.Client.V2.Gitlab.GitlabRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The groups property</summary>
        public global::YandexContestClient.Client.V2.Groups.GroupsRequestBuilder Groups
        {
            get => new global::YandexContestClient.Client.V2.Groups.GroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The participants property</summary>
        public global::YandexContestClient.Client.V2.Participants.ParticipantsRequestBuilder Participants
        {
            get => new global::YandexContestClient.Client.V2.Participants.ParticipantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The problems property</summary>
        public global::YandexContestClient.Client.V2.Problems.ProblemsRequestBuilder Problems
        {
            get => new global::YandexContestClient.Client.V2.Problems.ProblemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The service property</summary>
        public global::YandexContestClient.Client.V2.Service.ServiceRequestBuilder Service
        {
            get => new global::YandexContestClient.Client.V2.Service.ServiceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The submissions property</summary>
        public global::YandexContestClient.Client.V2.Submissions.SubmissionsRequestBuilder Submissions
        {
            get => new global::YandexContestClient.Client.V2.Submissions.SubmissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::YandexContestClient.Client.V2.Teams.TeamsRequestBuilder Teams
        {
            get => new global::YandexContestClient.Client.V2.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::YandexContestClient.Client.V2.User.UserRequestBuilder User
        {
            get => new global::YandexContestClient.Client.V2.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
