// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YandexContestClient.Client.V2.Gitlab.Submissions.Item.FileNamespace.Item;
namespace YandexContestClient.Client.V2.Gitlab.Submissions.Item.FileNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\gitlab\submissions\{submissionId}\file
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FileRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the YandexContestClient.Client.v2.gitlab.submissions.item.file.item collection</summary>
        /// <param name="position">fileId</param>
        /// <returns>A <see cref="global::YandexContestClient.Client.V2.Gitlab.Submissions.Item.FileNamespace.Item.WithFileItemRequestBuilder"/></returns>
        public global::YandexContestClient.Client.V2.Gitlab.Submissions.Item.FileNamespace.Item.WithFileItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("fileId", position);
                return new global::YandexContestClient.Client.V2.Gitlab.Submissions.Item.FileNamespace.Item.WithFileItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Gitlab.Submissions.Item.FileNamespace.FileRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FileRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/gitlab/submissions/{submissionId}/file", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Gitlab.Submissions.Item.FileNamespace.FileRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FileRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/gitlab/submissions/{submissionId}/file", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
