// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using YandexContestClient.Client.V2.Jupyter.Files;
namespace YandexContestClient.Client.V2.Jupyter
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\jupyter
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JupyterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The files property</summary>
        public global::YandexContestClient.Client.V2.Jupyter.Files.FilesRequestBuilder Files
        {
            get => new global::YandexContestClient.Client.V2.Jupyter.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.JupyterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JupyterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Jupyter.JupyterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JupyterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/jupyter", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
