// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using YandexContestClient.Client.Models;
namespace YandexContestClient.Client.V2.Contests.Item.StandingsExtended
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\contests\{contestId}\standings-extended
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StandingsExtendedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Contests.Item.StandingsExtended.StandingsExtendedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StandingsExtendedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/contests/{contestId}/standings-extended{?forJudge*,locale*,page*,pageSize*,participantId*,participantSearch*,showExternal*,showVirtual*,userGroupId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::YandexContestClient.Client.V2.Contests.Item.StandingsExtended.StandingsExtendedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StandingsExtendedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/contests/{contestId}/standings-extended{?forJudge*,locale*,page*,pageSize*,participantId*,participantSearch*,showExternal*,showVirtual*,userGroupId*}", rawUrl)
        {
        }
        /// <summary>
        /// Required scope: &lt;code&gt;manage&lt;/code&gt;This operation requires special permission. Use &lt;code&gt;/standings&lt;/code&gt; instead.
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.Models.ContestStandings"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::YandexContestClient.Client.Models.ContestStandings?> GetAsync(Action<RequestConfiguration<global::YandexContestClient.Client.V2.Contests.Item.StandingsExtended.StandingsExtendedRequestBuilder.StandingsExtendedRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::YandexContestClient.Client.Models.ContestStandings> GetAsync(Action<RequestConfiguration<global::YandexContestClient.Client.V2.Contests.Item.StandingsExtended.StandingsExtendedRequestBuilder.StandingsExtendedRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::YandexContestClient.Client.Models.ContestStandings>(requestInfo, global::YandexContestClient.Client.Models.ContestStandings.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Required scope: &lt;code&gt;manage&lt;/code&gt;This operation requires special permission. Use &lt;code&gt;/standings&lt;/code&gt; instead.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::YandexContestClient.Client.V2.Contests.Item.StandingsExtended.StandingsExtendedRequestBuilder.StandingsExtendedRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::YandexContestClient.Client.V2.Contests.Item.StandingsExtended.StandingsExtendedRequestBuilder.StandingsExtendedRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::YandexContestClient.Client.V2.Contests.Item.StandingsExtended.StandingsExtendedRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::YandexContestClient.Client.V2.Contests.Item.StandingsExtended.StandingsExtendedRequestBuilder WithUrl(string rawUrl)
        {
            return new global::YandexContestClient.Client.V2.Contests.Item.StandingsExtended.StandingsExtendedRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Required scope: &lt;code&gt;manage&lt;/code&gt;This operation requires special permission. Use &lt;code&gt;/standings&lt;/code&gt; instead.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StandingsExtendedRequestBuilderGetQueryParameters 
        {
            #pragma warning disable CS1591
            [QueryParameter("forJudge")]
            public bool? ForJudge { get; set; }
            #pragma warning restore CS1591
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("locale")]
            public string? Locale { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("locale")]
            public string Locale { get; set; }
            #pragma warning restore CS1591
#endif
            #pragma warning disable CS1591
            [QueryParameter("page")]
            public int? Page { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("participantId")]
            public long? ParticipantId { get; set; }
            #pragma warning restore CS1591
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("participantSearch")]
            public string? ParticipantSearch { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("participantSearch")]
            public string ParticipantSearch { get; set; }
            #pragma warning restore CS1591
#endif
            #pragma warning disable CS1591
            [QueryParameter("showExternal")]
            public bool? ShowExternal { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("showVirtual")]
            public bool? ShowVirtual { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("userGroupId")]
            public long? UserGroupId { get; set; }
            #pragma warning restore CS1591
        }
    }
}
#pragma warning restore CS0618
